function otopark_gui_simulasyon

fig = figure( ...
    'Name','Otopark Simulasyonu', ...
    'NumberTitle','off', ...
    'Position',[500 300 400 250], ...
    'MenuBar','none', ...
    'Resize','off');

uicontrol( ...
    'Style','text', ...
    'FontSize',18, ...
    'FontWeight','bold', ...
    'Position',[100 170 200 40], ...
    'String','OTOPARK');

durumText = uicontrol( ...
    'Style','text', ...
    'FontSize',16, ...
    'Position',[80 120 240 40], ...
    'String','DURUM: ---');

mesafeText = uicontrol( ...
    'Style','text', ...
    'FontSize',12, ...
    'Position',[80 80 240 30], ...
    'String','Mesafe: -- cm');

threshold = 40;

s = serialport("COM6",9600);   %COM port kontrol et
configureTerminator(s,"LF");
flush(s);

t = timer( ...
    'ExecutionMode','fixedRate', ...
    'Period',1, ...
    'TimerFcn',@updateGUI);

start(t);

    function updateGUI(~,~)
        if s.NumBytesAvailable > 0
            mesafe = str2double(readline(s));

            set(mesafeText,'String', ...
                sprintf('Mesafe: %.1f cm', mesafe));

            if mesafe > 0 && mesafe < threshold
                set(durumText,'String','DURUM: DOLU','ForegroundColor','r');
            else
                set(durumText,'String','DURUM: BOS','ForegroundColor','g');
            end
        end
    end

fig.CloseRequestFcn = @closeGUI;

    function closeGUI(~,~)
        stop(t);
        delete(t);
        clear s
        delete(fig);
    end
end
